### ISSUE TITLE
I have an error when i use ColumnSwitch on Table 

### ISSUE THREAD

**Issue by xuanco941** [AntdUI/AntdUI#12]
### 版本号

1.4.0

### .NET SDK

.NET Framework 45 以上

### 操作系统

Windows 10

### 如何复现

![Screenshot 2024-07-01 092928](https://github.com/AntdUI/AntdUI/assets/68849866/ff5a5242-6c7c-4ff4-b481-03c6a370a866)
When you press the status of a ColumnSwitch list continuously, you will get an error as shown in the image

### 异常信息

************** Exception Text **************
System.ArgumentException: Value of '16320' is not valid for 'alpha'. 'alpha' should be greater than or equal to 0 and less than or equal to 255.
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Color baseColor)
   at AntdUI.Table.PaintSwitch(Graphics g, TCellSwitch _switch)
   at AntdUI.Table.PaintItem(Graphics g, TCell it, SolidBrush fore)
   at AntdUI.Table.PaintItemFore(Graphics g, StyleRow row, SolidBrush fore)
   at AntdUI.Table.PaintTable(Graphics g, RowTemplate[] rows, Rectangle rect, Font column_font)
   at AntdUI.Table.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### 截图或视频

![Screenshot 2024-07-01 092928](https://github.com/AntdUI/AntdUI/assets/68849866/12c86ddd-1c8b-4039-b28a-93445d124c08)

**Comment by EVA-SS** [comment]
This issue has been fixed in the new version `1.4.2`
